server:
  port: 8082

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /test
    #开启rabbitmq的消费端重试机制,默认是false,默认重试 3 次
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
        acknowledge-mode: manual #采取手动应答
        #concurrency: 1 # 指定最小的消费者数量
        #max-concurrency: 1 #指定最大的消费者数量
      direct:
        acknowledge-mode: manual # 消费端手动ack消息
