server:
  port: 8081

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /test
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      retry:
        enabled: true